fullnameOverride: cloudesk-frontend

replicaCount: 2

image:
  repository: clouddesk/frontend
  tag: v1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: http

resources:
  requests:
    cpu: 50m
    memory: 32Mi
  limits:
    cpu: 200m
    memory: 128Mi
