apiVersion: v1
kind: Secret
metadata:
  name: {{ default (printf "%s-secret" (include "postgres.fullname" .)) .Values.secret.name }}
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.database.name | quote }}
  POSTGRES_USER: {{ .Values.database.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.secret.password | quote }}
