apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres.fullname" . }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "postgres.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
  - name: postgres
    port: {{ .Values.service.port }}
    targetPort: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres.fullname" . }}-hl
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: {{ include "postgres.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
  - name: postgres
    port: {{ .Values.service.port }}
    targetPort: postgres
