apiVersion: v1
kind: Secret
metadata:
  name: {{ default (printf "%s-secret" (include "backend.fullname" .)) .Values.secret.name }}
type: Opaque
stringData:
  DB_NAME: {{ .Values.database.name | quote }}
  DB_USER: {{ .Values.database.user | quote }}
  DB_PASSWORD: {{ .Values.secret.password | quote }}
  JWT_SECRET: {{ .Values.secret.jwt | quote }}