fullnameOverride: clouddesk-backend

replicaCount: 2
image:
  repository: clouddesk/backend
  tag: v1
config:
  APP_VERSION: v1
  APP_ENV: development
database:
  host: clouddesk-postgres.clouddesk.svc.cluster.local
  port: 5432
secret:
  jwt: dev-jwt-secret-change-me-0123456789abcdef
autoscaling:
  enabled: false
